FROM pytorch/pytorch
RUN apt-get update \
    && apt-get -y install git wget python3 python3-pip
RUN git clone https://github.com/Jacky2Wong/Covid-Research.git \
    && cd Covid-Research\
    && python3 -m pip install -r model-requirements.txt \
    && wget https://www.dropbox.com/s/j1epbu4ufunbbzv/lucene-index-covid-2020-03-27.tar.gz \
    && tar xvfz lucene-index-covid-2020-03-27.tar.gz \
    && rm -rf lucene-index-covid-2020-03-27.tar.gz
    
CMD ["python3", "inference.py"]
